### ISSUE TITLE
Not working in iOS app (non-beta)

### ISSUE THREAD

**Issue by paulbdavis** [iantrich/roku-card#30]
Updated to 1.0.7 and the card no longer responds to any touch events. Imported as a module, using the lates iOS app and 0.101.3

**Comment by iantrich** [comment]
I'll look into it

**Comment by iantrich** [comment]
@paulbdavis what version of iOS do you run and on what Apple device?

**Comment by paulbdavis** [comment]
It’s iOS 13.1 on an iPhone SE

>

**Comment by iantrich** [comment]
Was able to confirm on iPhone, iPad seems to be okay. I love mobile browsers... :see_no_evil: 

I don't have a solution yet, will have to do some further investigation.

**Comment by iantrich** [comment]
@paulbdavis looks to be wide spread, affecting anything that supports hold actions, even in core.

**Comment by crazifyngers** [comment]
From what I am seeing this isn't only the app, but also in browsers.  Though the app really looks like a web app.

**Comment by iantrich** [comment]
It's iOS in general

**Comment by iantrich** [comment]
fixed in https://github.com/iantrich/roku-card/releases/tag/1.0.9

**Comment by paulbdavis** [comment]
Hmm, I am still having issues with this card (as well as the restriction card you have in hacs) on iOS. Using the new beta app. This is on an iPhone SE if that makes a difference (there is no haptic feedback IIRC)

**Comment by iantrich** [comment]
@paulbdavis Can you try in a browser on your phone in a private session to verify it is not a caching issue?

**Comment by paulbdavis** [comment]
Phone browser has the same issue. 

I also tried clearing the front end cache in the app to no avail.

**Comment by iantrich** [comment]
I'm having no issues at all on my iPhone 7, running iOS 13.2.3

**Comment by Fabenissimo** [comment]
Tested it on my dad's iPhone 8 and my 11 Pro, both running iOS 13.2.3, the buttons don't work. I get the animation but nohing happens. Both devices using the now updated 2.0 (non beta) app.

**Comment by iantrich** [comment]
I guess share your config; not sure how it will help but somewhere to start. 

I'm on iOS 13.2.3 running 2.0 (non beta) as well. Only difference I can think of is that my card is in a popup.

**Comment by iantrich** [comment]
Do you get haptic feedback? That would mean that the action is being called but the remote is not triggering

**Comment by Fabenissimo** [comment]
Updated my config and added haptic-touch to my "down"-button. Didn't get any haptic feedback.
Here's my config: https://pastebin.com/AVMBVCHr

**Comment by Fabenissimo** [comment]
Wait... I just was able to use my volume-up and down buttons, they work on my iPhone but the rest of the buttons doesn't.

**Comment by iantrich** [comment]
You don't need to add haptic to your config, it is on by default for the iOS app

**Comment by iantrich** [comment]
@paulbdavis do have all your buttons with custom actions as well? Mine are the basic setup, not overriding any buttons. I'll test tonight with some overrides.

**Comment by iantrich** [comment]
I added a button override to the "down" button and it works perfectly. 🤷‍♂

**Comment by Fabenissimo** [comment]
What makes me wonder is that my volume controls work but the mute button doesn't. Are they used differently in the code?

**Comment by iantrich** [comment]
no, they are not. They are used in a common function as well...
https://github.com/iantrich/roku-card/blob/master/src/roku-card.ts#L98

**Comment by iantrich** [comment]
These all work for you in a desktop browser, correct?

**Comment by Fabenissimo** [comment]
Yes.

Just found out something new, I was wondering why the volume controls worked, the only thing in my config that was different for the volume/mute buttons was that the volume buttons had a "hold_action" defined as well.

Therefore I defined a hold_action for some other buttons in the card and they started working as well on my iPhone.

**Comment by paulbdavis** [comment]
@iantrich I did not have overrides set for any of the main buttons

I've tried out just adding a simple dummy hold action to all of the buttons and it started working on my phone again

just this was added to each button that didn't already have one (just my volume buttons, which were still working as @Fabenissimo mentioned) to get it working again, default actions still work

```yaml
{button name}:
  hold_action:
    action: call-service
```

**Comment by iantrich** [comment]
This is frustrating that I can't reproduce.
Only thing I can think to try is to have one, or both, of you setup a dev instance of the project and we can do some debugging. Would either of you be up for that?

**Comment by Fabenissimo** [comment]
Sure, what would you need from our side? A HA-instance to connect to?

**Comment by iantrich** [comment]
I added a [Developers](https://github.com/iantrich/roku-card/blob/master/README.md#developers) section to the readme.

If you're trying to access it from your phone, which you obviously will be, use the IP address of the local IP address of the machine hosting the project, not the `127.0.0.1` address

**Comment by iantrich** [comment]
If you use the fresh HA instance in the container, via `dc start` you'll need to update the [configuration.yaml](https://github.com/iantrich/roku-card/blob/master/.devcontainer/configuration.yaml) with your IP address of the Roku and the [ui-lovelace.yaml](https://github.com/iantrich/roku-card/blob/master/.devcontainer/ui-lovelace.yaml) file with the name of the roku media_player

**Comment by iantrich** [comment]
OR just use your existing instance and change the resources section once you have the devcontainer running

**Comment by Fabenissimo** [comment]
Ok, thanks for all the info. I'm a noob when it comes to git. I'll have to read into cloning and forking. As well es setting up the devcontainer (incl. Docker). Additionally I won't have that much time before the end of the week. Maybe @paulbdavis has more experience with all of that and will be able to set up the things you'll need to debug? If not I'll try to get all those things sorted by the end of this week.

**Comment by Fabenissimo** [comment]
Today I've set up the test system along with VS and docker. All for it to work in the test system. After a quick chat wit @iantrich I reinstalled the card via HACS and the buttons work now. @paulbdavis @crazifyngers  Maybe you can try to reinstall the card as well and see if that solves your issue (if you're on hacs, otherwise update the card manually via this guide: https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#updating-a-plugin
